/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindStationRouteImport } from './routes/find-station'
import { Route as RegisterStationRouteImport } from './routes/register-station'
import { Route as NavigateStationIdRouteImport } from './routes/navigate.$stationId'
import { Route as OwnerForgotPasswordRouteImport } from './routes/owner.forgot-password'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as OwnerSignupRouteImport } from './routes/owner.signup'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedOwnerDashboardRouteImport } from './routes/_authenticated/owner.dashboard'
import { Route as AuthenticatedOwnerStationsNewRouteImport } from './routes/_authenticated/owner.stations.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindStationRoute = FindStationRouteImport.update({
  id: '/find-station',
  path: '/find-station',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStationRoute = RegisterStationRouteImport.update({
  id: '/register-station',
  path: '/register-station',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateStationIdRoute = NavigateStationIdRouteImport.update({
  id: '/navigate/$stationId',
  path: '/navigate/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerForgotPasswordRoute = OwnerForgotPasswordRouteImport.update({
  id: '/owner/forgot-password',
  path: '/owner/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSignupRoute = OwnerSignupRouteImport.update({
  id: '/owner/signup',
  path: '/owner/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerDashboardRoute =
  AuthenticatedOwnerDashboardRouteImport.update({
    id: '/owner/dashboard',
    path: '/owner/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerStationsNewRoute =
  AuthenticatedOwnerStationsNewRouteImport.update({
    id: '/owner/stations/new',
    path: '/owner/stations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-station': typeof FindStationRoute
  '/register-station': typeof RegisterStationRoute
  '/navigate/$stationId': typeof NavigateStationIdRoute
  '/owner/forgot-password': typeof OwnerForgotPasswordRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/stations/new': typeof AuthenticatedOwnerStationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-station': typeof FindStationRoute
  '/register-station': typeof RegisterStationRoute
  '/navigate/$stationId': typeof NavigateStationIdRoute
  '/owner/forgot-password': typeof OwnerForgotPasswordRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/owner/stations/new': typeof AuthenticatedOwnerStationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-station': typeof FindStationRoute
  '/register-station': typeof RegisterStationRoute
  '/navigate/$stationId': typeof NavigateStationIdRoute
  '/owner/forgot-password': typeof OwnerForgotPasswordRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/owner/dashboard': typeof AuthenticatedOwnerDashboardRoute
  '/_authenticated/owner/stations/new': typeof AuthenticatedOwnerStationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/find-station'
    | '/register-station'
    | '/navigate/$stationId'
    | '/owner/forgot-password'
    | '/owner/login'
    | '/owner/signup'
    | '/stations/$stationId'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/stations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/find-station'
    | '/register-station'
    | '/navigate/$stationId'
    | '/owner/forgot-password'
    | '/owner/login'
    | '/owner/signup'
    | '/stations/$stationId'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/stations/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/find-station'
    | '/register-station'
    | '/navigate/$stationId'
    | '/owner/forgot-password'
    | '/owner/login'
    | '/owner/signup'
    | '/stations/$stationId'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/owner/dashboard'
    | '/_authenticated/owner/stations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FindStationRoute: typeof FindStationRoute
  RegisterStationRoute: typeof RegisterStationRoute
  NavigateStationIdRoute: typeof NavigateStationIdRoute
  OwnerForgotPasswordRoute: typeof OwnerForgotPasswordRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerSignupRoute: typeof OwnerSignupRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-station': {
      id: '/find-station'
      path: '/find-station'
      fullPath: '/find-station'
      preLoaderRoute: typeof FindStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-station': {
      id: '/register-station'
      path: '/register-station'
      fullPath: '/register-station'
      preLoaderRoute: typeof RegisterStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate/$stationId': {
      id: '/navigate/$stationId'
      path: '/navigate/$stationId'
      fullPath: '/navigate/$stationId'
      preLoaderRoute: typeof NavigateStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/forgot-password': {
      id: '/owner/forgot-password'
      path: '/owner/forgot-password'
      fullPath: '/owner/forgot-password'
      preLoaderRoute: typeof OwnerForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/signup': {
      id: '/owner/signup'
      path: '/owner/signup'
      fullPath: '/owner/signup'
      preLoaderRoute: typeof OwnerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/dashboard': {
      id: '/_authenticated/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof AuthenticatedOwnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/stations/new': {
      id: '/_authenticated/owner/stations/new'
      path: '/owner/stations/new'
      fullPath: '/owner/stations/new'
      preLoaderRoute: typeof AuthenticatedOwnerStationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedOwnerDashboardRoute: typeof AuthenticatedOwnerDashboardRoute
  AuthenticatedOwnerStationsNewRoute: typeof AuthenticatedOwnerStationsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedOwnerDashboardRoute: AuthenticatedOwnerDashboardRoute,
  AuthenticatedOwnerStationsNewRoute: AuthenticatedOwnerStationsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FindStationRoute: FindStationRoute,
  RegisterStationRoute: RegisterStationRoute,
  NavigateStationIdRoute: NavigateStationIdRoute,
  OwnerForgotPasswordRoute: OwnerForgotPasswordRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerSignupRoute: OwnerSignupRoute,
  StationsStationIdRoute: StationsStationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
