/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindStationRouteImport } from './routes/find-station'
import { Route as RegisterStationRouteImport } from './routes/register-station'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerForgotPasswordRouteImport } from './routes/owner.forgot-password'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as OwnerSignupRouteImport } from './routes/owner.signup'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'
import { Route as OwnerStationsNewRouteImport } from './routes/owner.stations.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindStationRoute = FindStationRouteImport.update({
  id: '/find-station',
  path: '/find-station',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStationRoute = RegisterStationRouteImport.update({
  id: '/register-station',
  path: '/register-station',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerForgotPasswordRoute = OwnerForgotPasswordRouteImport.update({
  id: '/owner/forgot-password',
  path: '/owner/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSignupRoute = OwnerSignupRouteImport.update({
  id: '/owner/signup',
  path: '/owner/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStationsNewRoute = OwnerStationsNewRouteImport.update({
  id: '/owner/stations/new',
  path: '/owner/stations/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-station': typeof FindStationRoute
  '/register-station': typeof RegisterStationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/forgot-password': typeof OwnerForgotPasswordRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/owner/stations/new': typeof OwnerStationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-station': typeof FindStationRoute
  '/register-station': typeof RegisterStationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/forgot-password': typeof OwnerForgotPasswordRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/owner/stations/new': typeof OwnerStationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-station': typeof FindStationRoute
  '/register-station': typeof RegisterStationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/forgot-password': typeof OwnerForgotPasswordRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/signup': typeof OwnerSignupRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/owner/stations/new': typeof OwnerStationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/find-station'
    | '/register-station'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/forgot-password'
    | '/owner/login'
    | '/owner/signup'
    | '/stations/$stationId'
    | '/owner/stations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/find-station'
    | '/register-station'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/forgot-password'
    | '/owner/login'
    | '/owner/signup'
    | '/stations/$stationId'
    | '/owner/stations/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/find-station'
    | '/register-station'
    | '/admin/dashboard'
    | '/owner/dashboard'
    | '/owner/forgot-password'
    | '/owner/login'
    | '/owner/signup'
    | '/stations/$stationId'
    | '/owner/stations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FindStationRoute: typeof FindStationRoute
  RegisterStationRoute: typeof RegisterStationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerForgotPasswordRoute: typeof OwnerForgotPasswordRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerSignupRoute: typeof OwnerSignupRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
  OwnerStationsNewRoute: typeof OwnerStationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-station': {
      id: '/find-station'
      path: '/find-station'
      fullPath: '/find-station'
      preLoaderRoute: typeof FindStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-station': {
      id: '/register-station'
      path: '/register-station'
      fullPath: '/register-station'
      preLoaderRoute: typeof RegisterStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/forgot-password': {
      id: '/owner/forgot-password'
      path: '/owner/forgot-password'
      fullPath: '/owner/forgot-password'
      preLoaderRoute: typeof OwnerForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/signup': {
      id: '/owner/signup'
      path: '/owner/signup'
      fullPath: '/owner/signup'
      preLoaderRoute: typeof OwnerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/stations/new': {
      id: '/owner/stations/new'
      path: '/owner/stations/new'
      fullPath: '/owner/stations/new'
      preLoaderRoute: typeof OwnerStationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FindStationRoute: FindStationRoute,
  RegisterStationRoute: RegisterStationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerForgotPasswordRoute: OwnerForgotPasswordRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerSignupRoute: OwnerSignupRoute,
  StationsStationIdRoute: StationsStationIdRoute,
  OwnerStationsNewRoute: OwnerStationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
